slam_toolbox:
  ros__parameters:
    # Robot frame setup
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    
    # SLAM mode
    mode: mapping  # Options: mapping, localization, offline_slam_async, offline_slam_sync
    
    # SLAM parameters
    use_pose_extrapolator: true
    map_update_interval: 5.0
    max_laser_range: 12.0  # Turtlebot 4 lidar range
    minimum_time_interval: 0.2
    transform_timeout: 0.2
    tf_buffer_duration: 30.
    stack_size_to_use: 40000000  # 40 MB
    enable_interactive_mode: false
    
    # Loop closure parameters
    loop_search_space: 8.0
    loop_match_minimum_chain_size: 3
    do_loop_closing: true
    
    # Scan matcher parameters
    resolution: 0.05
    submap_size: 1.0
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5
    
    # Motion model parameters
    alpha1: 0.1
    alpha2: 0.1
    alpha3: 0.1
    alpha4: 0.1
    alpha5: 0.1